
DOMAIN_SCHEMA = {
    '$LABEL': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ugid','ctime'],
        'fields': {
            'appid': { 'type': str },
            'ctime': { 'type': 'timestamp[ms]', 'out_name': 'applyTime' },
            'mid': { 'type': str },
            'ugid': { 'type': str, 'default': '', 'out_name': 'userId' },
            'utime': { 'type': None },
            'zuid': { 'type': str },
        },
        'out_name': 'application',
    },
    'ACQ01': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'path', 'remote_addr', 'sessionId'],
        'fields': {
            'appid': { 'type': str },
            'ctime': { 'type': 'timestamp[ms]' },
            'mid': { 'type': str },
            'path': { 'type': str },
            'remote_addr': { 'type': str },
            'sessionId': { 'type': str },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': None },
            'zuid': { 'type': str },
        },
    },
    'ACQ02': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'ch', 'eleId', 'path', 'remote_addr', 'sessionId', 'startTime', 'endTime', 'stayTime', 'val'],
        'fields': {
            'appid': { 'type': str },
            'ch': { 'type': str },
            'ctime': { 'type': 'timestamp[ms]' },
            'eleId': { 'type': str },
            'endTime': { 'type': 'timestamp[ms]' },
            'mid': { 'type': str },
            'path': { 'type': str },
            'remote_addr': { 'type': str },
            'sessionId': { 'type': str },
            'startTime': { 'type': 'timestamp[ms]' },
            'stayTime': { 'type': int },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': None },
            'val': { 'type': str },
            'zuid': { 'type': str },
        },
    },
    'ACQ03': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'ch', 'clickTime', 'eleId', 'path', 'remote_addr', 'sessionId'],
        'fields': {
            'appid': { 'type': str },
            'ch': { 'type': str },
            'clickTime': { 'type': 'timestamp[ms]' },
            'ctime': { 'type': 'timestamp[ms]' },
            'eleId': { 'type': str },
            'mid': { 'type': str },
            'path': { 'type': str },
            'remote_addr': { 'type': str },
            'sessionId': { 'type': str },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': None },
            'zuid': { 'type': str },
        },
    },
    # 'acq04': ['zuid','ugid','appid','utime','ctime','applyDuaration','endHtmlTime','htmlDuaration','jsDuaration','jsRealyTime','loadingHideTime','remote_addr','startHtmlTime'],
    # 'APP01': {
    #     'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
    #     'values': ['ctime', 'remote_addr', 'appName', 'versionCode'],
    #     'dedup': ['appName'],
    #     'fields': {
    #         'appid': { "type": str },
    #         'appName': { "type": str },
    #         'ctime': { 'type': 'timestamp[ms]' },
    #         'mid': { 'type': str },
    #         'remote_addr': { "type": str },
    #         'ugid': { 'type': str, 'default': '' },
    #         'utime': { "type": 'timestamp[s]' },
    #         'versionCode': { "type": str },
    #         'zuid': { 'type': str },
    #     },
    # },
    'BCC01': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'checkAliveButtonId'],
        'fields': {
            'appid': { 'type': str },
            'checkAliveButtonId': { 'type': str },
            'ctime': { 'type': 'timestamp[ms]', 'out_name': 'timestamp' },
            'mid': { 'type': str },
            'remote_addr': { 'type': str, 'out_name': 'ip' },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': 'timestamp[s]' },
            'zuid': { 'type': str },
        },
    },
    # 'sms01': ['zuid','ugid','appid','utime','ctime','content','date','phone','remote_addr'],
    # 'sms02': ['zuid','ugid','appid','utime','ctime','content','date','phone','remote_addr'],
    'DEV01': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'imei', 'imsi', 'model', 'nativePhoneNum', 'providersName', 'remote_addr', 'swv', 'sysVersion', 'wifimac'],
        'fields': {
            'appid': { 'type': str },
            'ctime': { 'type': 'timestamp[ms]', 'out_name': 'timestamp' },
            'imei': { 'type': str, 'out_name': 'deviceId' },
            'imsi': { 'type': str },
            'mid': { 'type': str },
            'model': { 'type': str },
            'nativePhoneNum': { 'type': str, 'out_name': None },
            'providersName': { 'type': str, 'out_name': None },
            'remote_addr': { 'type': str, 'out_name': 'ip' },
            'swv': { 'type': str, 'out_name': None },
            'sysVersion': { 'type': str, 'default': '', 'out_name': 'osVersion' },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': None },
            'wifimac': { 'type': str, 'out_name': None },
            'zuid': { 'type': str },
        },
        'out_name': 'device',
    },
    # 'dev02': ['zuid','ugid','appid','utime','ctime','remote_addr'],
    'CAL01': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'count', 'date', 'type', 'duration', 'name', 'number', 'remote_addr'],
        'dedup': ['date', 'type', 'duration'],
        'fields': {
            'appid': { 'type': str },
            'count': { 'type': int, 'out_name': None },
            'ctime': { 'type': 'timestamp[ms]', 'out_name': None },
            'date': { 'type': 'datetime[m]' },
            'duration': { 'type': lambda x: int(x) if x else 0 },
            'mid': { 'type': str },
            'name_masked': { 'type': str, 'out_name': None },
            'name': { 'type': str },
            'number_masked': { 'type': str, 'out_name': 'number' },
            'number_md5': { 'type': str },
            'number': { 'type': str },
            'remote_addr': { 'type': str, 'out_name': None },
            'type': { 'type': int },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': 'timestamp[s]' },
            'zuid': { 'type': str },
        },
        'out_name': 'calls',
    },
    'CON01': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'remote_addr', 'name', 'phone'],
        'dedup': ['phone'],
        'fields': {
            'appid': { 'type': str },
            'ctime': { 'type': 'timestamp[ms]', 'out_name': 'timestamp' },
            'mid': { 'type': str },
            'name_masked': { 'type': str, 'out_name': 'name' },
            'name': { 'type': str },
            'phone_masked': { 'type': str, 'out_name': 'number' },
            'phone_md5': { 'type': str, 'out_name': 'number_md5' },
            'phone': { 'type': str, 'out_name': 'number' },
            'remote_addr': { 'type': str, 'out_name': None },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': 'timestamp[s]' },
            'zuid': { 'type': str },
        },
        'out_name': 'contacts',
    },
    # 'eti01': ['zuid','ugid','appid','utime','ctime','editTextId','remote_addr','text'],
    'IDCARD01': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime','address','allTime','birthday','edit_address_time','edit_birthday_time','edit_id_card_number_time','edit_issuing_authority_time','edit_name_time','edit_period_of_validity_time','edit_race_time','gender','id_card_number','issued_by','name','race','remote_addr','statistic_back_idcard_recognition_count','statistic_face_recognition_count','statistic_front_idcard_recognition_count','valid_date'],
        'fields': {
            'address': { 'type': str },
            'allTime': { 'type': str, 'out_name': None },
            'appid': { 'type': str },
            'birthday': { 'type': str, 'out_name': None },
            'ctime': { 'type': 'timestamp[ms]', 'out_name': 'timestamp' },
            'edit_address_time': { 'type': int, 'out_name': None },
            'edit_birthday_time': { 'type': int, 'out_name': None },
            'edit_id_card_number_time': { 'type': int, 'out_name': None },
            'edit_issuing_authority_time': { 'type': int, 'out_name': None },
            'edit_name_time': { 'type': int, 'out_name': None },
            'edit_period_of_validity_time': { 'type': int, 'out_name': None },
            'edit_race_time': { 'type': int, 'out_name': None },
            'gender': { 'type': str },
            'id_card_number': { 'type': str, 'out_name': 'identity' },
            'issued_by': { 'type': str, 'out_name': None },
            'mid': { 'type': str },
            'name': { 'type': str, 'out_name': 'name' },
            'race': { 'type': str, 'out_name': 'ethicGroup' },
            'remote_addr': { 'type': str, 'out_name': None },
            'statistic_back_idcard_recognition_count': { 'type': int, 'out_name': None },
            'statistic_face_recognition_count': { 'type': int, 'out_name': None },
            'statistic_front_idcard_recognition_count': { 'type': int, 'out_name': None },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': 'timestamp[s]' },
            'valid_date': { 'type': str, 'out_name': None },
            'zuid': { 'type': str },
        },
        'out_name': 'basic',
    },
    # 'lcpagea01': ['zuid','ugid','appid','utime','ctime','appver','chanel','model','mt','noShowPage','page','remote_addr','unionId','userGid'],
    # 'loc01': ['zuid','ugid','appid','utime','ctime','ip','remote_addr'],
    'LOGIN01': {
        'keys': ['ugid', 'zuid', 'appid', 'mid', 'utime'],
        'values': ['ctime', 'loginFromType'],
        'fields': {
            'appid': { 'type': str },
            'loginFromType': { 'type': str },
            'ctime': { 'type': 'timestamp[ms]', 'out_name': 'timestamp' },
            'mid': { 'type': str },
            'remote_addr': { 'type': str, 'out_name': 'ip' },
            'ugid': { 'type': str, 'default': '' },
            'utime': { 'type': 'timestamp[s]' },
            'zuid': { 'type': str },
        },
    },
}
